package:
  name: holoviews
  version: 1.5.0

source:
  path: .

requirements:
  build:
    - python
    - param
    - setuptools
  run:
    - python
    - param
    - numpy
    - matplotlib
    - bokeh
    - jupyter
    - notebook
    - ipython
    - lancet

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause