package:
  name: holoviews
  version: 1.8.1

source:
  path: .

requirements:
  build:
    - python
    - param
    - numpy
    - setuptools
  run:
    - python
    - param >=1.5.1,<2.0
    - numpy
    - matplotlib
    - bokeh >=0.12.6
    - jupyter
    - notebook
    - ipython

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
