{% set sdata = load_setup_py_data(setup_file="../setup.py", from_recipe_dir=True) %}

package:
  name: holoviews
  version: {{ VERSION }}

source:
  url: ../dist/panel-{{ VERSION }}-py3-none-any.whl

build:
  noarch: python
  script: {{ PYTHON }} -m pip install -vv holoviews-{{ VERSION }}-py3-none-any.whl
  entry_points:
    {% for group,epoints in sdata.get("entry_points",{}).items() %}
    {% for entry_point in epoints %}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata['extras_require']['build'] %}
    - {{ dep }}
    {% endfor %}
  run:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata.get('install_requires',{}) %}
    - {{ dep }}
    {% endfor %}
    {% for dep in sdata['extras_require']['recommended'] %}
    - {{ dep }}
    {% endfor %}


about:
  home: https://holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
