{% set sdata = load_setup_py_data() %}

package:
  name: holoviews
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py --quiet install --single-version-externally-managed --record record.txt
  entry_points:
    {% for group,epoints in sdata.get("entry_points",{}).items() %}
    {% for entry_point in epoints %}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata['extras_require']['build'] %}
    {% if "python_version<" not in dep %}
    {% set dep_parts = dep.split(';') %}
    - {{ dep_parts[0]|trim }}
    {% endif %}
    {% endfor %}
  run:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata.get('install_requires',{}) %}
    {% if "python_version<" not in dep %}
    {% set dep_parts = dep.split(';') %}
    - {{ dep_parts[0]|trim }}
    {% endif %}
    {% endfor %}
    {% for dep in sdata['extras_require']['recommended'] %}
    {% if "python_version<" not in dep %}
    {% set dep_parts = dep.split(';') %}
    - {{ dep_parts[0]|trim }}
    {% endif %}
    {% endfor %}

test:
  requires:
    - nose
  imports:
    - holoviews
  commands:
    - nosetests holoviews.tests.core holoviews.tests.element holoviews.tests.plotting.bokeh --with-doctest

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
