{% set sdata = load_setup_py_data() %}

package:
  name: holoviews
  version: {{ sdata['version'] }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    
requirements:
  build:
    - python
    - param
    - numpy
    - setuptools
  run:
    - python
    - param >=1.5.1,<2.0
    - numpy
    - matplotlib
    - bokeh>=0.12.14,<=0.12.15
    - jupyter
    - notebook
    - ipython

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
