{% set sdata = load_setup_py_data() %}

package:
  name: holoviews
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py --quiet install --single-version-externally-managed --record record.txt
  entry_points:
    - holoviews = holoviews.util.command:main

requirements:
  build:
    - python
    - param >=1.6.1,<2.0
    - numpy
    - setuptools
  run:
    - python
    - param >=1.8.0,<2.0
    - pyviz_comms >=0.7.0
    - numpy
    - matplotlib>=2.1
    - bokeh >=1.1.0dev8
    - notebook
    - ipython >=5.4.0,<=7.1.1  # <=7.1.1 due to tab completion regression

test:
  requires:
    - nose
  imports:
    - holoviews
  commands:
    - nosetests holoviews.tests --with-doctest

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
