name: downstream_tests

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: [packages]
    types: [completed]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  downstream_tests:
    name: Run downstream tests
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push') || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        downstream_repo: [hvplot, geoviews]
      fail-fast: false
    steps:
      - uses: holoviz-dev/holoviz_tasks/downstream-tests@ba69594cc0818936bdf628134c86267016a4ef6d # v1.0.8
        with:
          downstream_repo: ${{ matrix.downstream_repo }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
