name: optimize-png
on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      run-all:
        description: "Run on all PNG files"
        type: boolean
        default: false

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  optimize_png:
    name: optimize-png
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: holoviz-dev/holoviz_tasks/optimize-png@optimize-png
        with:
          run-all: ${{ inputs.run-all || false }}
