name: title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: holoviz-dev/holoviz_tasks/validate-pr-title@ffddda04b2894fea39b407f64d3622d2f19e5a9f # v1
        with:
          title: ${{ github.event.pull_request.title }}
          types: |
            build
            chore
            ci
            compat
            docs
            enh
            feat
            fix
            perf
            refactor
            test
            type
          scopes: |
            dev
            data
            plotting
            bokeh
            matplotlib
            plotly
            notebook
